# permissions for end users to edit nifis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nifi-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nifi-operator
    app.kubernetes.io/part-of: nifi-operator
    app.kubernetes.io/managed-by: kustomize
  name: nifi-editor-role
rules:
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - nifis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - nifis/status
  verbs:
  - get
